example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import create

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='ajax'),
    path('ajax/submit/', create, name='form'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http.response import JsonResponse


@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Mazaya Nur Labiba',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Mazaya Nur Labiba',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def create(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        item = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        item.save()
        return JsonResponse({"instance": "Proyek Dibuat"}, status=200)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="print.css" media="print">
        <title>Login</title>
    </head>
    <body>
        <div class = "login">   
            <h1>Login</h1>
            <form method="POST" action="">
            {% csrf_token %}
            <table align="center">
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                    
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
                <!-- <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr> -->
            </table>
            <input class="btn login_btn" type="submit" value="Login"><a href="{% url 'wishlist:show_wishlist' %}"></a>
            </form>
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}    
            <p>Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a></p>
        </div>
    </body>
</html>

<style>
    body {
        background-color: #bfdbd2;
    }
    .login {
        text-align: center;
        margin: auto;
        padding-top: 130px;
    }
    input {
        display: inline-block;
        text-align: left;
    }
    button {
        text-decoration: center;
        margin:2px;
    }
    p {
        margin:2px;
    }
</style>

wishlist/templates/register.html
<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="print.css" media="print">
        <title>Register</title>
    </head>
    <body>
        <div class = "register d-flex justify-content-center align-items-center;">
            <h2>Formulir Registrasi</h2>  
                <form method="POST">  
                    {% csrf_token %}  
                    <table align="center" style="padding-top:0px;">  
                        {{ form.as_table }}  
                    </table> 
                </div>
                <div class="rapper">
                    <input class="btn register_btn" type="submit" value="Daftar"><a href="{% url 'wishlist:login' %}"></a> 
                </div>
                </form>
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        </div>  
    </body>
</html> 

<style>
    body {
        background-color: #bfdbd2;
    }
    body h2 {
        text-align: center;
    }
    .register {
        text-align: left;
        margin: auto;
        padding-top: auto;
    }
    input {
        text-align: left;
    }
    .rapper {
        text-align:center;
    }
</style>

wishlist/templates/wishlist.html
<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="print.css" media="print">
        <title>Wishlist</title>
    </head>
    <body>
        <nav>
            <ul>
                <li><h5>Nama: {{nama}}</h5></li>
                <li><button><a href="{% url 'wishlist:logout' %}">Logout</a></button></li>
            </ul>
        </nav> 
        <div class="non-header">
            <table border="1" align="center">
                <tr>
                <th>Nama Barang</th>
                <th>Harga Barang</th>
                <th>Deskripsi</th>
                </tr>
                {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                {% for barang in list_barang %}
                <tr>
                    <th>{{barang.nama_barang}}</th>
                    <th>{{barang.harga_barang}}</th>
                    <th>{{barang.deskripsi}}</th>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="footer">
            <h5>Sesi terakhir login: {{ last_login }}</h5>
        </div>
    </body>
</html>

<style>
    nav {
        margin:auto;
        text-align: center;
        width: 100%;
        font-family: arial;
    }
    nav ul {
        background: white;
        padding: auto;
        list-style: none;
        position: relative;
        display: inline-table;
        width: 100%;
    }
    nav ul li h5{
        float:left;
    }
    nav ul li button{
     	color: #fff;
        float:right;
        padding:auto;
        margin-top:20px;
        margin-right:60px;
    }
    body {
        background-color: #bfdbd2;
        margin:auto;
    }
    .non-header {
        margin: 10px;
    }
    .footer {
        margin:20px;
        text-align:center;
    }
    table {
        background-color: white;
    }
</style>

wishlist/templates/wishlist_ajax.html
<!-- <!doctype html>
    <html lang="en">
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="print.css" media="print">
        <title>Wishlist</title>
        <script>
            function loadData() {
                            $.get("{% url 'wishlist:show_json' %}", function (data) {
                tab = `<tr>
                        <th>Nama Barang</th>
                        <th>Harga Barang</th>
                        <th>Deskripsi</th>
                    </tr>`;

                for (let item of data) {
                    tab += `<tr> 
                    <td>${item.fields.nama_barang} </td>
                    <td>${item.fields.harga_barang}</td>
                    <td>${item.fields.deskripsi}</td> 
                    </tr>`;}

                document.getElementById("tbl").innerHTML = tab;
                });
            }

            $(document).ready(function () {
                loadData();
            });

            $(document).on("submit", "#formtable", function (e) {
                e.preventDefault();
                $.ajax({
                type: "POST",
                url: "wishlist.html",
                data: {
                    nama_barang: $("#items_name").val(),
                    harga_barang: $("#items_pr").val(),
                    deskripsi: $("#items_descrip").val(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                dataType: "json",
                success: function () {
                    loadData();
                },
                });
            });
        </script>  
    </head>
    <body>
        <script>
            function yaa() {
                if (localStorage.clickcount) {
                    localStorage.clickcount = Number(localStorage.clickcount)+1;
                } else {
                    localStorage.clickcount = 1;
                }
            }
        </script>
        <nav>
            <ul>
                <li><h5>Nama: {{nama}}</h5></li>
                <li><button><a href="{% url 'wishlist:logout' %}">Logout</a></button></li>
            </ul>
        </nav> 
        <form method="POST" action="">
            {% csrf_token %}
            <h1 class="h1 mb-3 fw-semibold">INPUT</h1>
    
            <div class="form-floating">
                <label for="Nama Barang">Nama Barang</label>
                <input type="nama" class="form-control" id="Nama Barang" placeholder="Nama Barang" name="Nama Barang">
            </div>
            <div class="form-floating">
                <label for="Harga Barang">Harga Barang</label>
                <input type="harga" class="form-control" id="Harga Barang" placeholder="Harga Barang" name="Harga Barang">
            </div>
            <div class="form-floating">
                <label for="Deskripsi">Deskripsi</label>
                <input type="deskripsi" class="form-control" id="Deskripsi" placeholder="Deskripsi" name="Deskripsi">
            </div>
            <button type="button" onclick="yaa()">Submit</button>
    
            {% if messages %}
                {% for message in messages %}
                    <p class="text-muted">{{ message }}</p>
                {% endfor %}
            {% endif %}                
        </form>  
        <div class="non-header">
            <table border="1" align="center">
                <tr>
                <th>Nama Barang</th>
                <th>Harga Barang</th>
                <th>Deskripsi</th>
                </tr>
                {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                {% for barang in list_barang %}
                <tr>
                    <th>{{barang.nama_barang}}</th>
                    <th>{{barang.harga_barang}}</th>
                    <th>{{barang.deskripsi}}</th>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="footer">
            <h5>Sesi terakhir login: {{ last_login }}</h5>
        </div>
    </body>
</html>

<style>
    nav {
        margin:auto;
        text-align: center;
        width: 100%;
        font-family: arial;
    }

    nav ul {
        background: white;
        padding: auto;
        list-style: none;
        position: relative;
        display: inline-table;
        width: 100%;
    }

    nav ul li h5{
        float:left;
    }

    nav ul li button{
     	color: #fff;
        float:right;
        padding:auto;
        margin-top:20px;
        margin-right:60px;
    }

    body {
        background-color: #bfdbd2;
        margin:auto;
        text-align: center;
    }

    .non-header {
        margin: 10px;
    }

    .footer {
        margin:20px;
        text-align:center;
    }

    table {
        background-color: white;
    }

    form {
      padding: 25px;
      text-align: center;
      align-items: center;
      width: 100%;
    }

    form .form-floating:focus-within {
      z-index: 1;
    }

    form input[type="nama"] {
      margin-bottom: 5px;
    }

    form input[type="harga"] {
      margin-bottom: 5px;
    }

    form input[type="deskripsi"] {
      margin-bottom: 5px;
    }
</style> -->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg bg-warning">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">{{nama}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
        </div>
    </nav>
    <div class="d-flex justify-content-center">

    </div>

    <table class="table-striped-columns table-bordered d-flex justify-content-center" id="tbl">
    </table>
    <h5 class="d-flex justify-content-center">Sesi terakhir login: {{ last_login }}</h5>

    <div>
      <form method="POST" action="" id="formtable" class="d-flex justify-content-center p-2  ">
        <div class="bg-danger d-flex justify-content-center p-2 rounded-2 p-3">
          {% csrf_token %}
          <table>
            <tr>
                <td>Nama Barang: </td>
                <td><input type="text" name="items" placeholder="Nama Barang" class="form-control" id="items_name"></td>
            </tr>
            <tr>
                <td>Harga Barang: </td>
                <td><input type="text" name="items_price" placeholder="Harga Barang" class="form-control" id="items_pr"></td>
            </tr>
            <tr>
                <td>Deskripsi: </td>
                <td><input type="text" name="items_desc" placeholder="Deskripsi" class="form-control" id="items_descrip"></td>
            </tr>
            
            
            </table>
            <button onclick="clickCounter()" type="submit" id="masuk" class="btn border rounded bg-info mx-2">Tambah</button>
        </div>
      
        
      </form>
     </div> 
  </body>
</html>
    
<script>

let tab;
  function loadData() {
    $.get("{% url 'wishlist:show_json' %}", function (data) {
      tab = `<tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
          </tr>`;

      for (let item of data) {
        tab += `<tr> 
        <td>${item.fields.nama_barang} </td>
        <td>${item.fields.harga_barang}</td>
        <td>${item.fields.deskripsi}</td> 
        </tr>`;}

    document.getElementById("tbl").innerHTML = tab;
    });
  }

  $(document).ready(function () {
    loadData();
  });

  $(document).on("submit", "#formtable", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'wishlist:form' %}",
      data: {
        nama_barang: $("#items_name").val(),
        harga_barang: $("#items_pr").val(),
        deskripsi: $("#items_descrip").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      dataType: "json",
      success: function () {
        loadData();
      },
    });
  });

  function clickCounter() {
    if (localStorage.clickcount) {
        localStorage.clickcount = Number(localStorage.clickcount)+1;
    } else {
        localStorage.clickcount = 1;
    }
}
</script>